### ISSUE TITLE
[✨ FEATURE] 현재 인기 경매를 메인에 게시합니다.

### ISSUE THREAD

**Issue by na0th** [TaskSprints/auction#10]
## ✨ 기능 설명
특정 기준에 따라 현재 인기 경매를 표시합니다.

## ❓ 왜 필요한가요?
많은 참여자들의 입찰이 이뤄질 수 있도록 합니다.

## 💡 해결 방법 제안
조회수, 입찰 빈도, 경매 즐겨찾기 수 등을 기준으로 경매를 표시합니다.

## 🔄 대안
고려할 수 있는 대안이나 추가적인 해결책을 기입해주세요.

## 📝 추가 사항
여기에 제안하는 기능에 대한 다른 추가 사항을 기입해주세요.

**Comment by KNU-K** [comment]
현재 통합 filter 기반 검색과 비슷한 부분이라 issue 닫겠습니다.

* #44
